name: RHOAI Build must-gather image

on:
  push:
    tags:
      - 'rhoai-*'
jobs:
    build-and-publish-operator:
      name: Build and (or) Publish Image
      runs-on: ubuntu-latest  
      steps:        
        - name: Checkout code
          uses: actions/checkout@v4

        - name: Build image 
          id: build-image
          uses: redhat-actions/buildah-build@v2
          with:
            image: quay.io/modh/must-gather
            tags: ${{ steps.meta.outputs.tags }} stable latest
            platforms: linux/amd64
            containerfiles: |
              Dockerfile

        - name: Login to Quay.io
          id: podman-login-quay
          if: startsWith(github.ref, 'refs/tags/rhoai-')
          shell: bash
          run: |
              podman login --username ${{ secrets.QUAY_USERNAME }} --password ${{ secrets.QUAY_TOKEN }} quay.io

        - name: Push to Quay.io
          if:  steps.podman-login-quay.outcome == 'success' 
          id: push-to-quay
          uses: redhat-actions/push-to-registry@v2
          with:
            image: ${{ steps.build-image.outputs.image }}
            tags: ${{ steps.build-image.outputs.tags }}