---
name: Linter

on:
  pull_request:
    branches:
    - main
    - master
    - 'rhoai-[0-9].[0-9]'

permissions:
  contents: read

jobs:
  super-linter:
    permissions:
      contents: read
      statuses: write

    name: Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0
      - name: Run Super-Linter
        uses: github/super-linter@v5.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          FILTER_REGEX_INCLUDE:  .*collection-scripts/.*
